apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 name: agent
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
apiVersion: v1
items:
- apiVersion: agent-install.openshift.io/v1beta1
  kind: AgentServiceConfig
  metadata:
    finalizers:
    - agentserviceconfig.agent-install.openshift.io/local-cluster-import-deprovision
    - agentserviceconfig.agent-install.openshift.io/ai-deprovision
    generation: 4
    name: agent
  spec:
    databaseStorage:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: database
    filesystemStorage:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: filesystem
    imageStorage:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: image
kind: List
metadata:
  resourceVersion: ""
