apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "ztp-amx1"
  namespace: "ztp-amx1"
spec:
  baseDomain: "amx.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.14.15-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMhXg/nJGNxkb0XTzu+asl7Q0iwLJFvkSzXXiUgJIDfyICnePgGOsdNawLtLkXai+JWNdYdgv9MLaHD85UEjN9/Dzd428Pl2lNjCnLAiYVOrzAQAnjmh8N+YLgUkS/U3iicpYyJRKv7RCnHK86+gaghU1xSyvIQ3y08ePmD3KP7A/qQ8GWAs3Qu/ohA8UwI6xFZvi32EUHyUOFu4SPwXlqUQ5LP4KV3IlwoilaVc11JXv0ijus1mvvrXqeCPD0tyy7RbLxOTt2d/Ndv0a4l1c7/HdWKcdyFXkdBOc6CpkzrMhnxBv3HIRVIgineVO6U1+6sdSeqJjRixCiBp5xxaMhg3nMkT/IYdv377VK0DfEZBlqHxgeMFR2O+FqTHeJbEMf2+tuCUhSsG1UQ9cODo1CgygnTbAIfCl97tuki6698dRJqNfC5xbzIlZADZgLO86s6vH/oPUQIt4bvrHywvSXXwA62oEXbhriUwkE1GuCJA4sCyZaRYNSi1C61KSYQOM= root@kvmpre01.mgmt-pre.amx.com"
  clusters:
  - clusterName: "ztp-amx1"
    networkType: "OVNKubernetes"
    holdinstallation: false
    clusterLabels:
      cluster: ztp-amx1
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.26.64/26
    # For 3-node and standard clusters with static IPs, the API and Ingress IPs must be configured here
    apiVIP: 192.168.26.69
    apiVIPs:
      - 192.168.26.69
    ingressVIP: 192.168.26.70
    ingressVIPs:
      - 192.168.26.70
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - 192.168.19.10
      # - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    # Optionally; This can be used to to configure desired BIOS setting on all nodes in this cluster:
    #biosConfigRef:
    #  filePath: "example-hw.profile"
################################################################
    nodes:
      - hostName: "master0.ztp-amx1.amx.com"
        role: "master"
        vendor: Dell
        bmcAddress: "idrac-virtualmedia://192.168.20.117/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "bmh-secret"
        bootMACAddress: "00:90:FA:9A:8A:94"
        bootMode: "legacy"  
        #bootMode: "UEFI"  
        # Use UEFI to enable secure boot for this node
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: ""
#        rootDeviceHints:
#          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f1"
              macAddress: "00:90:FA:9A:8C:14"
            - name: "enp7s0f1"
              macAddress: "00:90:FA:9A:8A:94"
            - name: "eno3"
              macAddress: "ec:f4:bb:db:2b:c4"
          config:
            interfaces:
              - name: eno3
                type: ethernet
                state: up
                identifier: name
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  dhcp: false
                  address: 
                  - ip: 192.168.26.9
                    prefix-length: 27
                  enabled: true
                ipv6:
                  enabled: false
              - name: bond0 
                type: bond
                state: up
                identifier: name
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
                link-aggregation:
                  mode: 802.3ad
                  options:
                    miimon: 100
                  port:
                  - enp5s0f1
                  - enp7s0f1
              - name: bond0.233 
                type: vlan
                state: up
                vlan:
                  base-iface: bond0
                  id: 233
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  enabled: true
                  dhcp: false
                  address:
                  - ip: 192.168.26.73
                    prefix-length: 26
              - name: enp5s0f1
                type: ethernet
                state: up
                ipv4:
                  address:
                  enabled: false
                ipv6:
                  enabled: false
              - name: enp7s0f1
                type: ethernet
                state: up
                ipv4:
                  address:
                  enabled: false
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                server:
                  - 10.1.198.36
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-address: 10.1.198.46
                  next-hop-interface: bond0.233
############################################################
      - hostName: "master1.ztp-amx1.amx.com"
        role: "master"
        vendor: Dell
        bmcAddress: "idrac-virtualmedia://192.168.20.82/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "bmh-secret"
        bootMACAddress: "00:90:FA:9A:78:BC"
        bootMode: "legacy"
        #bootMode: "UEFI"
        # Use UEFI to enable secure boot for this node
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: ""
#        rootDeviceHints:
#          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f1"
              macAddress: "00:90:FA:9A:78:5C"
            - name: "enp7s0f1"
              macAddress: "00:90:FA:9A:78:BC"
            - name: "eno3"
              macAddress: "ec:f4:bb:da:e0:1c"
          config:
            interfaces:
              - name: eno3
                type: ethernet
                state: up
                identifier: name
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  dhcp: false
                  address:
                  - ip: 192.168.26.10
                    prefix-length: 27
                  enabled: true
                ipv6:
                  enabled: false
              - name: bond0
                type: bond
                state: up
                identifier: name
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
                link-aggregation:
                  mode: 802.3ad
                  options:
                    miimon: 100
                  port:
                  - enp5s0f1
                  - enp7s0f1
              - name: bond0.233
                type: vlan
                state: up
                vlan:
                  base-iface: bond0
                  id: 233
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  enabled: true
                  dhcp: false
                  address:
                  - ip: 192.168.26.74
                    prefix-length: 26
              - name: enp5s0f1
                type: ethernet
                state: up
                ipv4:
                  address:
                  enabled: false
                ipv6:
                  enabled: false
              - name: enp7s0f1
                type: ethernet
                state: up
                ipv4:
                  address:
                  enabled: false
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                server:
                  - 10.1.198.36
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-address: 10.1.198.46
                  next-hop-interface: bond0.233
############################################################
      - hostName: "master2.ztp-amx1.amx.com"
        role: "master"
        vendor: Dell
        bmcAddress: "idrac-virtualmedia://192.168.20.83/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "bmh-secret"
        bootMACAddress: "00:90:FA:9A:79:0C"
        bootMode: "legacy"
        #bootMode: "UEFI"
        # Use UEFI to enable secure boot for this node
        nodeLabels:
          cluster.ocs.openshift.io/openshift-storage: ""
#        rootDeviceHints:
#          deviceName: "/dev/sda"
# As per: https://docs.openshift.com/container-platform/4.11/scalability_and_performance/cnf-talm-for-cluster-upgrades.html#cnf-about-topology-aware-lifecycle-manager-config_cnf-topology-aware-lifecycle-manager
        #diskPartition:
        #  - device: /dev/sda
        #    partitions:
        #    - mount_point: /var/recovery
        #      size: 51200
        #      start: 800000
        nodeNetwork:
          interfaces:
            - name: "enp5s0f1"
              macAddress: "00:90:FA:9A:84:6C"
            - name: "enp7s0f1"
              macAddress: "00:90:FA:9A:79:0C"
            - name: "eno3"
              macAddress: "ec:f4:bb:da:de:d4"
          config:
            interfaces:
              - name: eno3
                type: ethernet
                state: up
                identifier: name
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  dhcp: false
                  address:
                  - ip: 192.168.26.11
                    prefix-length: 27
                  enabled: true
                ipv6:
                  enabled: false
              - name: bond0
                type: bond
                state: up
                identifier: name
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
                link-aggregation:
                  mode: 802.3ad
                  options:
                    miimon: 100
                  port:
                  - enp5s0f1
                  - enp7s0f1
              - name: bond0.233
                type: vlan
                state: up
                vlan:
                  base-iface: bond0
                  id: 233
                mtu: 9000
                min-mtu: 68
                max-mtu: 65535
                wait-ip: any
                ipv4:
                  enabled: true
                  dhcp: false
                  address:
                  - ip: 192.168.26.75
                    prefix-length: 26
              - name: enp5s0f1
                type: ethernet
                state: up
                ipv4:
                  address:
                  enabled: false
                ipv6:
                  enabled: false
              - name: enp7s0f1
                type: ethernet
                state: up
                ipv4:
                  address:
                  enabled: false
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                server:
                  - 10.1.198.36
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-address: 10.1.198.46
                  next-hop-interface: bond0.233
